services:
  - type: web
    name: auction-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: COOKIE_EXPIRE
        value: 7
      - key: CLOUDINARY_NAME
        value: ds2neoo6i
      - key: CLOUDINARY_API_KEY
        value: 485522417296364
      - key: CLOUDINARY_API_SECRET
        value: 0bupzasK_v42rpMbnkMaQ6fDOqM
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 